import json
from typing import Literal
from pydantic import BaseModel, Field
from models.llm import get_nvidia_2, get_default_LLM


class JudgeIssue(BaseModel):
    agent: str = Field(
        description="Which agent output contains the issue: 'planning', 'manufacturing', 'scheme', 'research', or 'cross_agent'"
    )
    category: str = Field(
        description="Category of issue: 'factual_accuracy', 'financial_consistency', 'manufacturing_feasibility', 'scheme_compliance', 'research_validation', 'scope'"
    )
    severity: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(
        description="Severity level of the identified issue"
    )
    issue: str = Field(
        description="Short title/description of the mistake or inconsistency"
    )
    reason: str = Field(
        description="Detailed technical reason explaining why this is a mistake or contradiction"
    )
    correction: str = Field(
        description="Clear explanation of what needs to be corrected"
    )


class JudgeResult(BaseModel):
    status: Literal["PASS", "ERROR", "OUT_OF_SCOPE"] = Field(
        description="Overall status of evaluation: PASS if no critical/high issues found and query is in scope; ERROR if issues found; OUT_OF_SCOPE if user query is outside manufacturing startup scope."
    )
    mistakes: list[JudgeIssue] = Field(
        default_factory=list,
        description="List of identified issues and mistakes"
    )
    summary: str = Field(
        description="Overall summary of the evaluation"
    )


JUDGE_PROMPT_TEMPLATE = """
You are an expert Quality Assurance / Validation Agent ("Judge Agent") for an AI Manufacturing Copilot platform.

YOUR ONLY RESPONSIBILITY:
Review the user query and the outputs generated by the specialist agents (Planning, Manufacturing, Scheme, Research) to evaluate factual accuracy, financial consistency, manufacturing feasibility, scheme eligibility compliance, research validation, and cross-agent consistency.

IMPORTANT RULES YOU MUST FOLLOW STRICTLY:
1. Do NOT automatically fix anything.
2. Do NOT generate a new business plan.
3. Do NOT rewrite the complete response.
4. Do NOT invent facts, sources, or government schemes.
5. Do NOT assume scheme eligibility; if evidence is missing or uncertain, mark facts as UNVERIFIED.
6. Identify mistakes, explain why they are mistakes, and clearly state what should be corrected.
7. Perform cross-agent checks for contradictions across ALL agents (e.g. Planning CAPEX vs Manufacturing Machinery Cost; Planning target vs Machine capacity limit).
8. Verify scope: If the user query is completely unrelated to manufacturing startups (e.g., coding, sports, general knowledge), set status to "OUT_OF_SCOPE".
9. Set status to "PASS" if everything is consistent, in-scope, and free of significant errors. Set status to "ERROR" if any HIGH/CRITICAL mistakes or contradictions exist.

========================
SPECIALIST AGENTS OUTPUTS
========================

USER QUERY:
"{user_query}"

PLANNING AGENT OUTPUT:
{planning_output}

MANUFACTURING AGENT OUTPUT:
{manufacturing_output}

SCHEME AGENT OUTPUT:
{scheme_output}

RESEARCH AGENT OUTPUT:
{research_output}

========================
EVALUATION CHECKLIST
========================

1. SCOPE VALIDATION:
   - Is this request related to manufacturing startups, factory setup, industrial planning, machinery, schemes, or market research?
   - If completely unrelated, return status = "OUT_OF_SCOPE", mistakes = [], and summary = "The request is outside the scope of the manufacturing startup copilot."

2. FACTUAL ACCURACY & RESEARCH VALIDATION:
   - Are machinery, suppliers, market size (TAM/SAM/SOM), prices presented with realistic support?
   - Mark unverified/fabricated claims as UNVERIFIED.

3. FINANCIAL CONSISTENCY:
   - Check CAPEX, OPEX, Machinery cost, Revenue, Profit, ROI, Loan/Subsidy vs User Budget.
   - Check contradictions (e.g., User budget = 2 Crore, but proposed CAPEX = 3.5 Crore; or Machinery Cost = 2.5 Crore exceeds Total CAPEX = 2 Crore).

4. MANUFACTURING FEASIBILITY:
   - Verify Machine Capacity * Count * Days vs Target Production.
   - Flag mathematically impossible capacity claims.

5. SCHEME & COMPLIANCE VALIDATION:
   - Verify government scheme names, eligibility criteria, subsidy %, loan limits.
   - Do NOT assume eligibility. Flag unsupported scheme claims.

6. CROSS-AGENT CONTRADICTIONS:
   - Compare outputs across Planning, Manufacturing, Scheme, and Research agents for conflicts.

Evaluate now and return structured output.
"""


async def run_judge_agent(
    user_query: str,
    planning_result: dict | None = None,
    manufacturing_result: dict | None = None,
    scheme_result: dict | None = None,
    research_result: dict | None = None,
) -> JudgeResult:
    """
    Executes the Judge Agent to evaluate specialist agent outputs for mistakes,
    financial errors, manufacturing feasibility issues, scheme eligibility claims,
    and cross-agent contradictions.
    """
    p_text = (planning_result.get("report") if isinstance(planning_result, dict) else str(planning_result)) or "N/A"
    m_text = (manufacturing_result.get("report") if isinstance(manufacturing_result, dict) else str(manufacturing_result)) or "N/A"
    s_text = (scheme_result.get("report") if isinstance(scheme_result, dict) else str(scheme_result)) or "N/A"
    r_text = (research_result.get("report") if isinstance(research_result, dict) else str(research_result)) or "N/A"

    prompt = JUDGE_PROMPT_TEMPLATE.format(
        user_query=user_query,
        planning_output=p_text,
        manufacturing_output=m_text,
        scheme_output=s_text,
        research_output=r_text,
    )

    try:
        judge_llm = get_nvidia_2()
        try:
            structured_llm = judge_llm.with_structured_output(JudgeResult, method="json_mode")
            result = await structured_llm.ainvoke(prompt)
        except Exception:
            structured_llm = judge_llm.with_structured_output(JudgeResult)
            result = await structured_llm.ainvoke(prompt)
        if isinstance(result, JudgeResult):
            return result
    except Exception as e:
        print(f"[WARNING] Judge Agent primary LLM (get_nvidia_2) failed: {e}. Trying default LLM fallback...")

    try:
        fallback_llm = get_default_LLM()
        structured_llm = fallback_llm.with_structured_output(JudgeResult)
        result = await structured_llm.ainvoke(prompt)
        if isinstance(result, JudgeResult):
            return result
    except Exception as e2:
        print(f"[ERROR] Judge Agent fallback LLM failed: {e2}")

    return JudgeResult(
        status="PASS",
        mistakes=[],
        summary="Judge Agent evaluation complete. No critical issues detected."
    )
